name        : libxdmcp
version     : 1.1.2
release     : 7
source      :
    - http://xorg.freedesktop.org/releases/individual/lib/libXdmcp-1.1.2.tar.bz2 : 81fe09867918fff258296e1e1e159f0dc639cb30d201c53519f25ab73af4e4e2
license     :
    - MIT
summary     : X Display Manager Control Protocol library
builddeps   :
    - pkgconfig(xproto)
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : true
description : |
    X Display Manager Control Protocol library
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
