name       : libxdmcp
version    : 1.1.3
release    : 16
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libXdmcp-1.1.3.tar.gz : 2ef9653d32e09d1bf1b837d0e0311024979653fe755ad3aaada8db1aa6ea180c
license    : MIT
component  : xorg.library
summary    : X Display Manager Control Protocol library
description: |
    X Display Manager Control Protocol library
emul32     : true
optimize   : speed
builddeps  :
    - pkgconfig(xproto)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
